title: [Плагин СДЭК для wordpress woocommerce]
description: [Калькулятор стоимости доставки курьерской службой СДЭК]
markdown: kramdown
show_downloads: ["true"]
google_analytics: [UA-21586186-3]
theme: jekyll-theme-cayman
